services:
  front_end:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - 1234:80
    volumes:
      - . /FrontEnd:/app

  back_end:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./BackEnd:/server
      - /server/node_modules
  
  mongodb:
    image: mongo:latest
    container_name: wmd_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data: