services:
  front_end:
    build:
      context: ./FrontEnd   # <--- TERUG NAAR FRONTEND
      dockerfile: Dockerfile
    ports:
      - "1234:80"           # Je frontend blijft op poort 1234
    volumes:
      - ./FrontEnd:/usr/share/nginx/html

  back_end:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: wmd_backend
    ports:
      - "5050:5050"         # We gebruiken poort 5050
    environment:
      - PORT=5050
      - MONGO_URI=mongodb://wmd_mongo:27017/wmd_project
    volumes:
      - ./BackEnd:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: wmd_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: